"""empty message

Revision ID: 7f546be6f342
Revises: a0b22a722267
Create Date: 2023-06-08 16:03:51.978671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f546be6f342'
down_revision = 'a0b22a722267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_author_id_fkey', 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###
